### ISSUE TITLE
OpenShift 4.7 Content Refresh (1/?)

### ISSUE THREAD

**Issue by ryanj** [openshift-labs/learn-katacoda#1101]
I'm creating this issue to track progress on our OpenShift 4.7 content refresh:

New content:
- [x] [OpenShift 4-7 playground](https://learn.openshift.com/playgrounds/openshift47/)

Moved to `openshift-4-7`:
- [x] [Getting Started with ArgoCD and OpenShift GitOps Operator](https://learn.openshift.com/gitops/getting-started/) #1112
- [x] [Working with Kustomize](https://learn.openshift.com/gitops/kustomize/) #1112
- [x] [Syncwaves and Hooks](https://learn.openshift.com/gitops/syncwaves-and-hooks/) #1112
- [x] [Logging in to an OpenShift Cluster](https://learn.openshift.com/introduction/cluster-access/) #1113
- [x] [Transferring Files in and out of Containers](https://learn.openshift.com/introduction/transferring-files/) #1113
- [x] [Connecting to a Database Using Port Forwarding](https://learn.openshift.com/introduction/port-forwarding/) #1113
- [x] [Using the CLI to Manage Resource Objects](https://learn.openshift.com/introduction/resource-objects/) #1113
- [x] [Deploying Applications From Images](https://learn.openshift.com/introduction/deploying-images/) #1113
- [x] [Deploying Applications From Source](https://learn.openshift.com/introduction/deploying-python/) #1113
- [x] [How to set up Prometheus and Grafana on OpenShift](https://learn.openshift.com/introduction/deploy-prometheus-grafana/) #1113
- [x] [Getting Started with OpenShift for Developers](https://learn.openshift.com/introduction/getting-started/) #1113
- [x] [Deploying Applications From Source](https://learn.openshift.com/introduction/deploying-python/) #1113
- [x] [Developing with odo](https://learn.openshift.com/introduction/developing-with-odo/) #1113
- [x] [Connecting to a Database Using Port Forwarding](https://learn.openshift.com/introduction/port-forwarding/) #1113
- [x] [Transferring Files in and out of Containers](https://learn.openshift.com/introduction/transferring-files/) #1113
- [x] [Deploying a Jupyter Notebook Image](https://learn.openshift.com/ai-machine-learning/jupyter-notebooks/) #1113
- [x] [Building Custom Notebook Images](https://learn.openshift.com/ai-machine-learning/custom-notebooks/) #1113
- [x] [Persistent Workspace for Notebooks](https://learn.openshift.com/ai-machine-learning/jupyter-workspace/) #1113
- [x] [Deploying JupyterHub as a Service](https://learn.openshift.com/ai-machine-learning/jupyterhub-service/) #1113
- [x] [Multi-user Workspace Using JupyterHub](https://learn.openshift.com/ai-machine-learning/jupyterhub-workspace/) #1113
- [x] [Using OpenShift Pipelines](https://learn.openshift.com/middleware/pipelines/) #1119
- [x] [Getting Started with OpenShift Serverless](https://learn.openshift.com/developing-on-openshift/serverless/) #1121
- [x] [Getting Started with Helm 3 on OpenShift](https://learn.openshift.com/developing-on-openshift/helm/) #1123

**Comment by ryanj** [comment]
Initial migration complete!
